### ISSUE TITLE
Error on running zrunner on tutorial files

### ISSUE THREAD

**Issue by Martin-Jung** [cbig/ztools#4]
Hi,
I downloaded the 4.0 release for linux ( https://github.com/cbig/zonation-core/releases ).
Tried to execute `zrunner` with the tutorial basic tests files. 
```
~/zonation/zonation-4.0.0rc1_compact-GNU-Linux/bin$ zrunner -x ./zig4 ~/zonation/zonation-tutorial/basic/tests/ztests_basic.yaml 
Traceback (most recent call last):
  File "/usr/local/bin/zrunner", line 11, in <module>
    load_entry_point('ztools==0.2.dev20190313', 'console_scripts', 'zrunner')()
  File "/usr/local/lib/python2.7/dist-packages/ztools/runner.py", line 237, in main
    output['z_info'] = get_zonation_info(args.executable)
  File "/usr/local/lib/python2.7/dist-packages/ztools/utilities.py", line 68, in get_zonation_info
    version, errs = version.communicate()[0]
ValueError: need more than 0 values to unpack

```
Any advise is appreciated!

**Comment by Martin-Jung** [comment]
It seems that this has been reported before for zonation-core. Will attempt to find the source of the bug elsewhere
https://github.com/cbig/zonation-core/issues/15#issuecomment-290919085
